version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  db:
    image: pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rabbit
      POSTGRES_USER: rabbit
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pg.csv:/docker-entrypoint-initdb.d/pg.csv
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 5050:80
volumes:
  db:
